### ISSUE TITLE
Any way to speed up storm inference

### ISSUE THREAD

**Issue by adeelabbas** [sp-uhh/storm#12]
Hi,
I am getting very slow inference performance on RTX 3090 (less than 1x real time). Wondering if there is any way to speed up the algorithm while keeping decent quality (quality that's still better than denoiser-only mode)?

**Comment by jmlemercier** [comment]
Hi,
The inference with 20 steps and no corrector (as recommended in the paper) should be rather quick on GPU, definitely faster than real-time.
If you are looking for schemes to improve the inference speed, I'll suggest to wait two weeks, we have something in the making, or you can take a look at the existing literature on fast inference for diffusion-based generative models: most of them should be compatible with StoRM.

**Comment by egorsmkv** [comment]
@jmlemercier hi, did you release the second solution to the problem?

**Comment by jmlemercier** [comment]
Hi @egorsmkv this is actually ongoing work, should be released sometime around September!

**Comment by wangtiance** [comment]
Hi @jmlemercier , I'm also experiencing very slow inference with GPU. Is the September update going on as planned?

**Comment by jmlemercier** [comment]
Hi @wangtiance, again, we did not experience very slow inference on GPU with the settings provided (it worked in real-time with 20 steps as mentioned above). 
WRT few-step diffusion, I suggest you take a look at our recent arXiv pre-prints on the matter:
- a different SDE parameterisation for more accurate inference, completely compatible with the StoRM framework (simply change the SDE parameters accordingly): https://arxiv.org/abs/2302.14748
- a partially supervised version of SGMSE+ (competitive with StoRM down to 2 diffusion steps, then outperforms other method for 1 and 2-step solvers): https://arxiv.org/abs/2309.09677
