### ISSUE TITLE
Pretrained checkpoints have lower results than article results

### ISSUE THREAD

**Issue by CZ-2128** [sp-uhh/storm#13]
Hi, I'm learning a lot from your ideas.I downloaded the Voicebank/DEMAND checkpoint and got the following results: pesq=2.88 stoi=0.87 si-sdr=18.5 Is it the difference in enhancement settings that's causing this?
Current settings: 
mode : storm, corrector : ald, corrector-steps : 1, snr : 0.5, N : 50

**Comment by TianyuCao** [comment]
Hi, I got exactly the same results as yours. Did you finally figure it out?

**Comment by CZ-2128** [comment]
> Hi, I got exactly the same results as yours. Did you finally figure it out?

Hi, you can reduce sampling step N to 20-30.

**Comment by TianyuCao** [comment]
> > Hi, I got exactly the same results as yours. Did you finally figure it out?
> 
> Hi, you can reduce sampling step N to 20-30.

Sorry, I just saw your message. Do you mean if we reduce the inference steps from 50 (by default) to 20 or 30, then we can get higher results like what was shown in the paper? Thanks for your clarifications in advance.

Btw, did you have any chance to use their other pretrained checkpoint trained on WSJ0+Chime3? I also got lower results than article results, but tried to figure it out.
