### ISSUE TITLE
cuda environment issue

### ISSUE THREAD

**Issue by yunzqq** [sp-uhh/storm#14]
raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by jmlemercier** [comment]
Well as indicated by the error message, this error is due to your CUDA environment not being set, and has nothing to do with the repository. Type `nvcc --version` to see which CUDA version is installed on your machine, and downloda the according pytorch version. Not much I can do for you here.
