### ISSUE TITLE
Cuda issues

### ISSUE THREAD

**Issue by lianabagh** [sp-uhh/storm#15]
Hi, 

I am facing with cuda driver issues. Can you specify your nvcc cuda version, torch cuda version and gcc version?

**Comment by lianabagh** [comment]
And also GPU.

**Comment by lianabagh** [comment]
And also GPU driver cuda version ))

**Comment by jmlemercier** [comment]
Hi @lianabagh , the code for the ppaer ran on torch==1.10+cu11.6 with CUDA version 11.6
But definitely it should also work with more recent CUDA/torch configurations, as soon as they are aligned. I think the stable build is currently torch==2.2.0 with CUDA version 12.1

The GPU model should not have any importance, as soon as your CUDA driver supports it.

**Comment by jmlemercier** [comment]
Also, it can be that `ninja` poses problems with `torch`. If the error is caused by `ninja`, I'd recommend uninstalling both ninja torch and their dependencies, and reinstall them. 
Also, don't forget to clean your torch-cuda caches in `~/.cache/torch_extensions` after changing your torch / CUDA / ninja versions.

**Comment by lianabagh** [comment]
The problem is with ninja and it doesn't disappear after doing the changes
you suggest. What is your ninja version?

**Comment by jmlemercier** [comment]
I notice we actually removed the calls to `ninja` in the current implementation (since it was always causing problems), so I am not sure what your problem is.

**Comment by jmlemercier** [comment]
If you 1- clean your torch caches as mentioned 2- restart your machine to reinit your CUDA kernels 3- create a new environment and install the packages using the suggested `requirements.txt` (and optionally 4- re-restart your machine): does this still happen? and if yes, please share a MWE
