### ISSUE TITLE
Attention layer used in bottleneck

### ISSUE THREAD

**Issue by philgzl** [sp-uhh/storm#3]
In the paper, when discussing the network architecture and comparing NCSN++M with NCSN++, it is said that "the attention layer in the bottleneck is removed". However, it seems to me that by setting `attn_resolutions = (0,)` [here](https://github.com/sp-uhh/storm/blob/b44f6c14d62b4e0cef51e59252da5360f3061b90/sgmse/backbones/ncsnpp.py#L46), no attention layers are used at all except in the bottleneck layer [here](https://github.com/sp-uhh/storm/blob/b44f6c14d62b4e0cef51e59252da5360f3061b90/sgmse/backbones/ncsnpp.py#L211). This is also the case in the previous sp-uhh/sgmse repo ([here](https://github.com/sp-uhh/sgmse/blob/a1ac609a2f83f405f3c3be0c4120b6c0c94bf595/sgmse/backbones/ncsnpp.py#L447) and [here](https://github.com/sp-uhh/sgmse/blob/a1ac609a2f83f405f3c3be0c4120b6c0c94bf595/sgmse/backbones/ncsnpp.py#L204)). So it seems to me the correct statement describing the new model should be "the attention layers are removed except in the bottleneck layer".

**Comment by jmlemercier** [comment]
Hi!
You are absolutely right, we let the attention block in the  bottleneck, that is a mistake that comes from confusions during multiples experiments where we did indeed remove the bottleneck attention.
We will correct if we are getting accepted.
Thanks for reporting !
