### ISSUE TITLE
48k checkpoint

### ISSUE THREAD

**Issue by adeelabbas** [sp-uhh/storm#6]
Hi,
Do you have a checkpoint that's trained on 48k audio input?

**Comment by jmlemercier** [comment]
Hi Adeel, unfortunately not: however, you should be able to easily reproduce the conditions using the original VCTK with 48kHz sampling frequency and tweaking the filters lengths / number of channels.
We designed experiments for 32kHz audio and it seemed to work okay: cannot share the checkpoints unfortunately as the data has copyrights.
Best,
Jm
