### ISSUE TITLE
bad results for all the pre-trained model

### ISSUE THREAD

**Issue by danhuixie** [sp-uhh/storm#8]
Hello, I have tried to process a small piece of noisy wave, but all the pre-trained model output bad results like white-noise.
input wave's spectrum
<img width="1078" alt="1" src="https://user-images.githubusercontent.com/24372222/222881143-07775578-07c2-42e0-8d6c-5eda17be40ae.png">
output wave's spectrum

<img width="1055" alt="2" src="https://user-images.githubusercontent.com/24372222/222881154-d5ad87ff-5172-4b7a-bcf5-fa531771994c.png">

so , how to infer correctly?

**Comment by jmlemercier** [comment]
Dear danhuixie, 
Thanks for reporting, there was indeed a typo that came in the code with my last commit, an artifact from some old code causing the score network output to be (wrongly) divided twice by the noise level sigma. This has been corrected with the latest commit: I ran some dummy tests and it should work fine. Please pull and let me know if that works on your side
Best
Jim
